library(plyr)
library(tidyr)
library(ggplot2)
library(RColorBrewer)
library(leaflet)
library(sp)
library(plotly)
library(DT)
library(shinyjs)

table.TotalThroughputs <- read.csv("~/Croatia v3.1/data/TotalThroughputs.csv", stringsAsFactors = FALSE)
table.HourlyThroughputs <- read.csv("~/Croatia v3.1/data/HourlyThroughputs.csv", stringsAsFactors = FALSE)
table.RollingHourlyThroughputs <- read.csv("~/Croatia v3.1/data/RollingHourlyThroughputs.csv", stringsAsFactors = FALSE)
table.FuelBurnTrackMiles <- read.csv("~/Croatia v3.1/data/FuelBurnTrackMiles.csv", stringsAsFactors = FALSE)
table.FuelBurn <- read.csv("~/Croatia v3.1/data/FuelBurn.csv", stringsAsFactors = FALSE)
table.TrackMiles <- read.csv("~/Croatia v3.1/data/TrackMiles.csv", stringsAsFactors = FALSE)
table.Conflicts <- read.csv("~/Croatia v3.1/data/Conflicts.csv", stringsAsFactors = FALSE)
table.ConflictType <- read.csv("~/Croatia v3.1/data/ConflictType.csv", stringsAsFactors = FALSE)
table.LateralConflictType <- read.csv("~/Croatia v3.1/data/LateralConflictType.csv", stringsAsFactors = FALSE)
table.VerticalConflictType <- read.csv("~/Croatia v3.1/data/VerticalConflictType.csv", stringsAsFactors = FALSE)
table.ConflictsFlightPlanPhase <- read.csv("~/Croatia v3.1/data/ConflictsFlightPlanPhase.csv", stringsAsFactors = FALSE)
table.Severity <- read.csv("~/Croatia v3.1/data/Severity.csv", stringsAsFactors = FALSE)
table.VerticalSeverity <- read.csv("~/Croatia v3.1/data/VerticalSeverity.csv", stringsAsFactors = FALSE)
table.SectorOccupancy <- read.csv("~/Croatia v3.1/data/SectorOccupancy.csv", stringsAsFactors = FALSE)
table.SectorEntry <- read.csv("~/Croatia v3.1/data/SectorEntry.csv", stringsAsFactors = FALSE)
table.Workload <- read.csv("~/Croatia v3.1/data/Workload.csv", stringsAsFactors = FALSE)
table.SectorPolygons <- read.csv("~/Croatia v3.1/data/SectorPolygons.csv", stringsAsFactors = FALSE)
